from pathlib import Path
from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_ROW_HEIGHT_RULE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt

ROOT = Path(__file__).resolve().parents[1]

def cell_setup(cell, text, bold=False, size=7.7, font='Times New Roman'):
    cell.text=''
    p=cell.paragraphs[0]; p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before=Pt(0); p.paragraph_format.space_after=Pt(0); p.paragraph_format.line_spacing=1.0
    r=p.add_run(str(text)); r.font.name=font; r._element.rPr.rFonts.set(qn('w:eastAsia'),font); r.font.size=Pt(size); r.bold=bold
    cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
    tcPr=cell._tc.get_or_add_tcPr(); mar=OxmlElement('w:tcMar')
    for side,val in [('top','65'),('start','65'),('bottom','65'),('end','65')]:
        e=OxmlElement('w:'+side); e.set(qn('w:w'),val); e.set(qn('w:type'),'dxa'); mar.append(e)
    tcPr.append(mar); borders=OxmlElement('w:tcBorders')
    for edge in ('top','left','bottom','right','insideH','insideV'):
        e=OxmlElement('w:'+edge); e.set(qn('w:val'),'single'); e.set(qn('w:sz'),'8'); e.set(qn('w:color'),'000000'); borders.append(e)
    tcPr.append(borders)

def add_table(doc,title,headers,rows,widths,size=7.5):
    p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(8); p.paragraph_format.space_after=Pt(5)
    r=p.add_run(title); r.font.name='Times New Roman'; r._element.rPr.rFonts.set(qn('w:eastAsia'),'Times New Roman'); r.font.size=Pt(12.5); r.bold=True
    t=doc.add_table(rows=1,cols=len(headers)); t.autofit=False
    tr=t.rows[0]; tr.height=Inches(.58); tr.height_rule=WD_ROW_HEIGHT_RULE.AT_LEAST
    hp=tr._tr.get_or_add_trPr(); rep=OxmlElement('w:tblHeader'); rep.set(qn('w:val'),'true'); hp.append(rep)
    for i,h in enumerate(headers): cell_setup(tr.cells[i],h,True,size); tr.cells[i].width=Inches(widths[i])
    for row in rows:
        cells=t.add_row().cells; t.rows[-1].height=Inches(.43); t.rows[-1].height_rule=WD_ROW_HEIGHT_RULE.AT_LEAST
        for i,v in enumerate(row): cell_setup(cells[i],v,False,size); cells[i].width=Inches(widths[i])
    doc.add_paragraph()

def body(doc,text):
    p=doc.add_paragraph(); p.paragraph_format.space_after=Pt(5); p.paragraph_format.line_spacing=1.05
    r=p.add_run(text); r.font.name='Times New Roman'; r._element.rPr.rFonts.set(qn('w:eastAsia'),'Times New Roman'); r.font.size=Pt(9)

def base_doc():
    d=Document(); s=d.sections[0]; s.orientation=WD_ORIENT.LANDSCAPE; s.page_width,s.page_height=s.page_height,s.page_width
    s.top_margin=s.bottom_margin=Inches(.55); s.left_margin=s.right_margin=Inches(.55); return d

datasets_en=[
['P00','NextGen','Device-day battery response','5 min','p_{i,t}, q_{i,t}, s_{i,t}, E_i, P_i^max, a_{i,t}, z_i, t','Measured traces; repeated days are not independent sources','100 sources / 3,000 device-days','Battery and network reference'],
['P00b','data2','Charging-session response','5 min','p_{i,t}, E_i, P_i^max, a_{i,t}, z_i, t','Measured sessions; input channel is counterfactual','Configuration-limited','Bidirectional charging stress'],
['P01','BDG1','Building electricity','Hourly','Load kW; building ID; calendar/time','Measured load; no PV/SOC','507','Building heterogeneity and minimum scale'],
['P02','Low Carbon London','Household electricity','30 min','Import energy; tariff; household ID; time','Measured load; no device-level battery fields','5,000','Large residential population'],
['P03','BDG2','Building electricity and solar','Hourly','Electricity; solar channels; building ID; time','Measured electricity; solar only for aligned subset','1,570','Mixed measured/counterfactual input'],
['P04','Danish heat meters','District-heating demand','Hourly','Thermal energy; meter ID; building context; time','Thermal proxy; not direct electrical power','2,400','Thermal-demand response diversity'],
['P05','Smart Grid Smart City','Customer load and generation','30 min','General load; controlled load; gross/net generation; customer ID; time','Measured load and generation fields','600','Measured-input and self-consumption analysis'],
['P06','HEAPO','Heat-pump household electricity','15 min/daily','Heat-pump electricity; weather; household ID; inspection metadata','Measured demand; storage fields are fallback','1,362','Heat-pump demand heterogeneity'],
['P07','GoiEner','Smart-meter electricity','Hourly','Consumption; customer ID; contract power; self-generation type','Measured load; self-generation flag is not a PV trace','5,000','Large-user load diversity'],
['P08','European LV urban-8k','LV customer P profiles','24/168 points','P profile; customer ID; feeder/GIS context','Measured profile with network context','5,000','Urban feeder customer diversity'],
['P09','European LV rural','LV customer P/Q profiles','24/168 points','Active/reactive power; customer ID; rural topology','Measured P/Q; Q retained for audit','2,731','Rural topology and spatial diversity'],
['P10','European LV urban-35k','LV customer P/Q profiles','24/168 points','Active/reactive power; customer ID; urban topology','Measured P/Q; large source inventory','12,000','Large urban network population'],
['P11','Norway AMI','MV/LV AMI load and generation','Hourly','Active import/export; reactive power; network model; weather/price','Measured-only AMI profiles','2,994','Network-linked measured evidence'],
['P12','CAMSL-JP','Smart-meter electricity','30 min','Consumption; tariff group; household metadata; temperature','Measured load; no external input trace','1,423','Tariff and temporal response'],
['P13','Irish CER','Household import/export','30 min','Import/export kWh; meter ID; timestamp','Measured bidirectional load','2,904','Bidirectional household diversity'],
['P14','OPSD','Household load, PV and devices','15 min','Load; PV; storage/EV/heat-pump channels; household ID','Only 11 independent households; bootstrap stress test','11','Small-source limitation audit'],
['P15','COMPLETE-EC','Energy-community load, PV, BESS, EV','15 min','Load; PV; battery capacity/SOC; EV capacity/SOC; location','Measured community profiles; 250 members','250','Integrated prosumer/community test'],]

datasets_zh=[[r[0],r[1],{'Building electricity':'建筑用电','Household electricity':'家庭用电','Building electricity and solar':'建筑用电与太阳能','District-heating demand':'区域供热需求','Customer load and generation':'客户负荷与发电','Heat-pump household electricity':'热泵家庭用电','Smart-meter electricity':'智能电表用电','LV customer P profiles':'低压客户有功轮廓','LV customer P/Q profiles':'低压客户有功/无功轮廓','MV/LV AMI load and generation':'中低压 AMI 负荷与发电','Smart-meter electricity':'智能电表用电','Household import/export':'家庭输入/输出','Household load, PV and devices':'家庭负荷、光伏与设备','Energy-community load, PV, BESS, EV':'能源社区负荷、光伏、电池与电动车'}.get(r[2],r[2]),r[3],r[4],r[5],r[6],{'Building heterogeneity and minimum scale':'建筑异质性与最小规模','Large residential population':'大规模住宅群体','Mixed measured/counterfactual input':'实测/反事实混合输入','Thermal-demand response diversity':'热需求响应多样性','Measured-input and self-consumption analysis':'实测输入与自消费分析','Heat-pump demand heterogeneity':'热泵需求异质性','Large-user load diversity':'大规模用户负荷多样性','Urban feeder customer diversity':'城市馈线客户多样性','Rural topology and spatial diversity':'农村拓扑与空间多样性','Large urban network population':'大规模城市网络群体','Network-linked measured evidence':'网络关联实测证据','Tariff and temporal response':'费率与时间响应','Bidirectional household diversity':'双向家庭负荷多样性','Small-source limitation audit':'小来源数量限制审计','Integrated prosumer/community test':'综合产消者/社区测试'}.get(r[7],r[7])] for r in datasets_en]

url_rows=[['BDG1','https://github.com/buds-lab/the-building-data-genome-project','Miller and Meggers, Energy Procedia (2017), DOI 10.1016/j.egypro.2017.07.400'],['Low Carbon London','https://data.london.gov.uk/dataset/smartmeter-energy-use-data-in-london-households','London Datastore / UK Power Networks project'],['BDG2','https://github.com/buds-lab/building-data-genome-project-2','Miller et al., Scientific Data (2020), DOI 10.1038/s41597-020-00712-x'],['Danish heat meters','https://zenodo.org/records/6563114','Schaffer et al., Scientific Data (2022), DOI 10.1038/s41597-022-01502-3'],['Smart Grid Smart City','https://data.gov.au/data/dataset/4e21dea3-9b87-4610-94c7-15a8a77907ef','Australian SGSC project'],['HEAPO','https://zenodo.org/records/15056919','HEAPO preprint, arXiv:2503.16993'],['GoiEner','https://zenodo.org/records/7362094','WHY project / GoiEner cooperative'],['European LV urban-8k','https://data.mendeley.com/datasets/685vgp64sm/1','DOI 10.17632/685vgp64sm.1'],['European LV rural / urban-35k','https://data.mendeley.com/datasets/gspyzvvrhm/2','DOI 10.17632/gspyzvvrhm.2'],['Norway AMI','https://data.mendeley.com/datasets/jv3rz8k35r/1','Maree, Energy distribution models with AMI smart meter sensor dataset'],['CAMSL-JP','https://data.mendeley.com/datasets/cmpsyncmmk/1','Kiguchi et al., CAMSL dataset'],['Irish CER','https://figshare.com/articles/dataset/6_150_years_1_month_17_days_and_8_hours_of_anonymised_electricity_smart_meter_data/31851922','Smeaton, Cai and Chen, DOI 10.6084/m9.figshare.31851922'],['OPSD','https://open-power-system-data.org/data-sources','Open Power System Data household data'],['COMPLETE-EC','https://zenodo.org/records/7602546','Faia et al., Data in Brief (2023), DOI 10.1016/j.dib.2023.109218']]

def make(lang='en'):
    d=base_doc(); title='Supplementary Tables S1, S4 and S5' if lang=='en' else '补充表 S1、S4 和 S5'
    p=d.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; r=p.add_run(title); r.font.name='Times New Roman'; r.font.size=Pt(16); r.bold=True
    if lang=='en':
        body(d,'These tables define the evidence chain from empirical population diversity to information-limited control and finally to physical network feasibility. The source count is the number of distinct source identifiers available after preprocessing; simulated device-days are reported separately and are not treated as independent empirical devices.')
        add_table(d,'Supplementary Table S1. Empirical population characteristics, standardized variables and data features.', ['ID','Dataset','Resource / signal','Resolution','Standardized variables','Measurement status','Source count','Data feature'],datasets_en,[.35,.9,1.0,.55,2.25,1.8,.6,1.35],5.8)
        body(d,'We use a common notation for all sources: i indexes a resource, t a dispatch interval, τ the sampling interval, p_{i,t} active power, q_{i,t} reactive power, s_{i,t} state of charge, E_i usable energy capacity, P_i^max maximum power, a_{i,t} availability, z_i feeder/zone assignment, g_{i,t} external generation or charging input, b_{i,t} baseline demand, and P_t=Σ_i p_{i,t} the aggregate response. NextGen supplies rich device-day battery traces for parameter and network calibration, but its approximately 100 independent sources mean that repeated days are not equivalent to 3,000 independent devices. data2 supplies five-minute charging sessions for bidirectional response and availability stress tests. BDG1 and BDG2 characterize building load; BDG2 additionally contains aligned solar channels for a subset. Low Carbon London, GoiEner and CAMSL-JP provide household or smart-meter demand, while Irish CER explicitly records import and export. SGSC contains general load, controlled load and gross/net generation, making it the principal measured-input source. HEAPO and Danish heat meters capture heat-pump and thermal-demand diversity; Danish observations remain a thermal proxy rather than measured electric power. European LV sources add P/Q profiles and feeder context, and Norway AMI combines measured P/Q with network information. COMPLETE-EC includes community load, PV, BESS and EV fields; OPSD has only 11 independent households and is therefore a small-source stress case. These variable and provenance differences are the data features used to interpret cross-dataset scaling.')
        add_table(d,'Supplementary Table S4. Control strategies, equations, required inputs and limitations.', ['Strategy','Equation / rule','Required inputs','Online information','Complexity','Purpose / limitation'],[['Open-loop','u_t is broadcast; p_{i,t}=u_t','r_t, τ','Broadcast only','O(1) operator-side','Lower reference; no state adaptation'],['Local SOC rule','p_{i,t}=clip(u_t; s_{i,t},P_i^max)','s_{i,t},P_i^max,a_{i,t}','Local state and limits','O(1)/device; O(N) fleet','Device baseline; no fleet coordination'],['MPC','min Σ_t(Σ_i p_{i,t}-r_t)^2 s.t. SOC,P/Q,V limits','r_t,s_i,E_i,P_i^max,q_i, network limits','Predictions, states, constraints','O(HN) variables; solver-dependent','Optimization reference; telemetry-heavy'],['Mean-field','p_{i,t}=π(x_{i,t},m_t), m_t=N^-1Σ_iφ(x_{i,t})','x_i=(s_i,a_i,p_i,q_i),φ','Moments plus local state','O(N) aggregation; O(1) broadcast','Scalable baseline; closure error'],['Virtual battery','P_t=clip(r_t,P_min(m_t),P_max(m_t))','s_i,E_i,P_i^max,a_i,t','Aggregate envelope','O(1) after fitting','Low-dimensional; envelope mismatch'],['Packetized','A_{i,t}~Bernoulli(ρ_t|s_i,a_i)','s_i,a_i, packet e_i','Request and local acceptance','O(N) actions; O(1) request','Asynchronous; delay/randomness'],['Transactive','p_i=argmax_p[v_i(p;x_i)-λ_t p], Σ_i p_i=r_t','x_i, tariff λ_t,r_t','Price and clearing','O(N log N) clearing','Market coordination; bid/convergence dependence'],['Hybrid / EPS','p_{i,t}=π_i(b_t,x_i,t); b_t=f(r_t,P_t^agg)','r_t, aggregate P_t, calibrated π_i','Broadcast plus aggregate feedback','O(1) routine; O(N) offline','Proposed strategy; calibration/drift/network layer'],['Centralized greedy upper bound','max Σ_i v_i(p_i) s.t. all device/network limits','All device states and network P/Q,V limits','Complete fleet and feeder state','O(N)-O(N log N) plus solver','Theoretical upper bound only; communication limits ignored; not deployable']], [1.35,2.25,2.0,1.45,1.15,2.8],5.9)
        body(d,'The equations specify the information contract. The reported protocol uses τ=300 s, prediction horizon H=12 intervals, R²≥0.95 as the prediction criterion, p_ctrl≥0.90 as the control criterion, and N_eff^*=500 as the effective-population reference. The EPS broadcast gain is calibrated offline; routine adaptation receives aggregate response P_t^agg rather than individual states. The centralized greedy controller is an information-unconstrained theoretical upper bound: it sees every device and feeder state and ignores communication limitations, so it is not a real implementation and is not claimed to be universally optimal. Complexity refers to the dominant coordination operation; power-flow and optimization costs depend on solver tolerances and network size.')
        add_table(d,'Supplementary Table S5. Physical variables, network-scale limits and questions addressed.', ['Environment','Scale','Physical variables / equations','Limits and stressors','Environment feature','Question'],[['Reference feeder','Reference','P_t=Σ_i p_i; A_net=P_acc/P_req','Reference limits; no topology claim','Comparator for threshold robustness','Is the aggregate boundary topology-stable?'],['IEEE-33','33 buses; 32 branches','P/Q flows; V_k; L_l=S_l/S_l^max; T=T_flow/T^max','L_l≤1; V_min≤V_k≤V_max; T≤1','Small radial feeder; interpretable bottlenecks','Which constraint clips a response first?'],['IEEE-69','69 buses; 68 branches','Same variables; z_i and concentration c_f','c_f=0.5; c_node=0.8; derating; M0-M6','Transfer and spatial stress','How do topology and placement change deliverability?'],['IEEE-123','123 buses; 122 branches','Same variables plus bus acceptance A_k','Transformer/voltage stress; direct-training audit','Largest radial representation','Does reduced-observability control remain feasible?'],['Constraint sweep','Each topology','A_net=P_acc/P_req; C_loss=1-A_net; R²','One of S_l^max,T^max,V_min,V_max varied','Separates statistics from physics','Can high R² coexist with low A_net?']], [1.15,1.2,2.55,2.2,1.8,2.0],5.8)
        body(d,'For branch l, S_l is apparent-power flow and S_l^max its thermal rating, so L_l=S_l/S_l^max≤1. At bus k, V_k must satisfy V_min≤V_k≤V_max. Transformer loading is T=T_flow/T^max≤1. Network acceptance is A_net=P_acc/P_req and the physically lost fraction is C_loss=1-A_net. The requested aggregate P_req is mapped through z_i before these inequalities are evaluated. IEEE-33 isolates interpretable branch and voltage bottlenecks; IEEE-69 tests feeder concentration c_f=0.5 and distal-node concentration c_node=0.8; IEEE-123 tests transfer to the largest radial representation. Constraint sweeps vary one of S_l^max, T^max, V_min or V_max while holding the remaining protocol fixed, separating high aggregate R² from low physical acceptance. These are constrained IEEE simulations, not field-safety certification.')
        add_table(d,'Data-source index used by Table S1.', ['Dataset','Public URL','Citation / note'],url_rows,[1.75,5.2,3.2],7.1)
    else:
        body(d,'这三张表构成从实证数据差异、信息受限控制到物理配电网可行性的证据链。source count 指预处理后可区分的独立来源数量；device-day 仿真样本另行处理，不能直接当作独立实测设备。')
        add_table(d,'补充表 S1。经验数据集特征、观测变量与研究用途。',['编号','数据集','资源/信号类型','时间分辨率','保留分析变量','实测状态与限制','来源数','回答的问题'],datasets_zh,[.45,1.2,1.25,.75,2.35,2.35,.72,1.55],6.8)
        body(d,'这些数据集的差异不只体现在规模，还体现在电负荷或热需求、单向或双向计量、是否包含发电和储能通道、时间分辨率，以及是否提供馈线或 GIS 信息。SGSC、BDG2 和 COMPLETE-EC 含有较丰富的发电或储能字段；负荷型数据集主要用于检验响应形状异质性。Danish 数据作为热需求代理，OPSD 和 COMPLETE-EC 明确属于小来源数量案例。这样的分层避免把大规模仿真 N 误读成广泛的实证覆盖。')
        add_table(d,'补充表 S4。控制策略、公式、信息需求与局限。',['策略','聚合控制公式/规则','与 S1 的变量衔接','在线信息','复杂度','作用','主要缺陷'],[['开环','u_i,t = u_t^broadcast','时间、负荷基线','仅广播信号','算子侧 O(1)','低阶参考','不能适应 SOC、可用性或约束'],['本地 SOC 规则','u_i,t = clip(u_t, SOC_i,t, P_i,max)','SOC、功率、容量、可用性','设备本地 SOC 与限制','每设备 O(1)；群体总计 O(N)','设备级基线','无群体协调，依赖阈值同质性'],['MPC','min Σ_t ||Σ_i u_i,t-r_t||²，满足 SOC/线路/电压约束','负荷、SOC、容量、功率、馈线 P/Q','预测、状态与约束','通常 O(HN) 变量；依赖求解器','优化参考','需要详细遥测与有效模型'],['均值场控制','u_i,t = π(x_i,t,m_t)，m_t=N⁻¹Σ_iφ(x_i,t)','状态 x=(SOC、可用性、负荷特征)','群体矩与本地状态','聚合 O(N)；广播 O(1)','均值场基线','强相关或漂移下闭合误差'],['虚拟电池','P_agg,t=clip(α_t,P_min(m_t),P_max(m_t))','SOC/容量分布与聚合包络','聚合状态估计','包络拟合后调度 O(1)','低维灵活性模型','包络失配会隐藏设备饱和'],['分组能量管理','accept_i,t~Bernoulli(p_t|SOC_i,t,request)','SOC、可用性、能量包、请求','请求与本地接受','设备动作 O(N)；请求 O(1)','异步随机基线','随机性和延迟降低跟踪精度'],['交易式控制','u_i,t=argmax_u[b_i(u;x_i,t)-λ_tu]；Σ_i u_i,t=r_t','负荷、SOC、费率/价格、约束','价格与聚合清算','排序/清算约 O(N log N)','市场式协调','需要竞价设计与迭代收敛'],['混合/EPS 广播','u_i,t=π_i(b_t,x_i,t)；b_t=f(r_t,aggregate feedback)','广播 b、聚合响应、SOC/可用性标定','广播与聚合测量','日常协调 O(1)；离线标定 O(N)','本文低可观测性策略','需要标定、漂移检测与网络可行性层'],['集中式贪心参考','在全部设备和网络约束下最大化 Σ_i value_i(u_i)','S1 全部设备与馈线变量','完整设备与网络状态','O(N) 至 O(N log N) 加网络求解器','可交付性参考','非普适最优，信息负担不现实']], [1.25,2.15,2.1,1.5,1.25,1.35,2.0],6.6)
        body(d,'公式明确了算法对 S1 变量的依赖。本地方法使用 SOC、可用性、容量和功率字段；聚合方法以矩或包络代替个体状态；MPC 与集中式参考还需要馈线 P/Q、电压和支路限制。复杂度表示主要协调步骤，优化和网络求解器成本取决于时域与具体形式。混合/EPS 的 O(1) 仅指日常广播通信维度，不包括注册、标定和模型维护。')
        add_table(d,'补充表 S5。物理变量、不同网络规模的限制与研究问题。',['环境','规模与拓扑','执行的物理变量','运行限制/压力','环境特点','主要探讨问题'],[['参考馈线','参考表示','聚合 P、请求/接受响应','参考限制；不作拓扑性能结论','用于阈值稳健性的共同对照','聚合控制边界在拓扑影响前是否稳定？'],['IEEE-33','33 母线；32 支路','P/Q 潮流、支路负载率、V_min/V_max、变压器负载率、母线位置','线路/变压器额定值、电压边界、正常与压力模式','小型径向馈线，瓶颈易解释','哪一类物理约束首先截断可控聚合响应？'],['IEEE-69','69 母线；68 支路','同上，增加馈线及末端节点集中','M0-M6；50% 馈线集中；80% 末端节点集中；降额','用于迁移和空间布置压力','拓扑和空间集中如何改变可交付性及方法顺序？'],['IEEE-123','123 母线；122 支路','P/Q 潮流、电压、变压器、支路及母线接受率','直接训练审计；变压器、电压和空间压力','最大规模径向表示','低信息策略在更大馈线是否仍保留可行效果？'],['约束扫描环境','以上各拓扑分别扫描','线路容量、变压器容量、V_min、V_max、接受率、弃电率、响应 R²','单独改变一个物理限制，其余按协议固定','分离统计保真度与物理可行性','高聚合 R² 是否能与低网络接受率同时存在？']], [1.35,1.55,2.6,2.3,1.95,2.0],6.8)
        body(d,'S5 将统计可控性与电气可交付性分开。聚合请求映射到母线后，再施加支路、电压和变压器限制。均匀布置、馈线集中和末端节点集中是不同的物理实验，而不是不同的统计群体。结果证明的是列出的 IEEE 模型下的仿真可行性，不等同于现场安全验证。')
        add_table(d,'S1 使用的数据来源索引。',['数据集','公开网址','引用/备注'],url_rows,[1.75,5.2,3.2],7.1)
    d.save(ROOT/('outputs/Supplementary_Tables_S1_S4_S5_English.docx' if lang=='en' else 'outputs/Supplementary_Tables_S1_S4_S5_Chinese.docx'))

if __name__=='__main__':
    make('en'); make('zh')
