paths: paths.yaml
original_model: original_model.yaml
simulation: simulation.yaml
population: population.yaml
source_device_map: source_device_map.yaml
zones: zones.yaml
network: network_ieee33.yaml
device_constraints: device_constraints.yaml
user_behavior: user_behavior.yaml
control: control.yaml
experiment: experiment_protocol.yaml
outputs: output_compatibility.yaml
